### PR TITLE
Remove database complexity

### PR DESCRIPTION
**Pull request by jmosbacher**
This is following a discussion to switch to a review process based on the github corrections repository.

Changes to the code:

- Database access is now via functions:
```
db = xedocs.straxen_db()
doc = db.avg_se_gains.find_one(version="ONLINE", run_id=25000)
```
- Corrections repo has its own dedicated constructor, which accepts the `branch` argument:
```
db = xedocs.correction_repo(branch="migrate_to_xedocs")
doc = db.avg_se_gains.find_one(version="ONLINE", run_id=25000)
```
- Conversion of run_id to time/time interval is dont using a root_validator on the schema instead of defining run_id as an alias of time. This avoids confusion when using the doc.dict and doc.json methods.
- Update API auth to use the new github based xeauth version

### CODE REVIEW

**Comment by LuisSanchez25** [comment]
Could we keep access to the development database in-built into xedocs as well? It might be useful for tests.

**Comment by jmosbacher** [comment]
> Could we keep access to the development database in-built into xedocs as well? It might be useful for tests.

Sure, added.

**Comment by jmosbacher** [comment]
@LuisSanchez25 can you run the tests you ran last time trying to process some data with this version of xedocs to verify nothing was broken? then if you can approve the changes that would be great, thanks!

**Comment by LuisSanchez25** [comment]
Sure I will take care of that later on tonight

**Comment by jmosbacher** [comment]
Merging and releasing for now to continue testing of the corrections repo. Will revert if we find any issues.

**Pull request merged**
