### PR TITLE
Update xedocs version

### PR DESCRIPTION
**Pull request by GiovanniVolta**
Given the 2 new schemas (avg_se_gain and avg_se_gain_partitioning), I have updated the xedocs version. We need to propagate this to the requirements of the other software.

### CODE REVIEW

**Comment by GiovanniVolta** [comment]
Question from a newbie: how does the release work?

**Review by Ananthu-Ravindran — APPROVED** [review]

**Comment by jmosbacher** [comment]
Hi, you should not bump versions manually. You should always use bump2version.
If you have poetry installed and you have installed the dev environment, you can run  `poetry run invoke bump`
Alternatively you can run `bump2version patch` then `git push` and `git push --tags`
this will create bump the version and create a git tag with the version. 
you can then create a release here on github from that tag.

**Comment by Ananthu-Ravindran** [comment]
@jmosbacher I released a new version [v0.2.27](https://github.com/XENONnT/xedocs/releases/tag/v0.2.27) using bump2version. I don't see the changes reflected on master. Do I have to make a separate commit-merge for it?

**Comment by jmosbacher** [comment]
what branch did you bump the version on? you should bump the version on master. if you bumped it on another branch then open a PR to merge it into master. Next time you can bump the version directly on master, just make sure the only change you make is the version and no other changes are committed before pushing to master.

**Comment by Ananthu-Ravindran** [comment]
Thankyou, I will do that from the next time.

I think [#123](https://github.com/XENONnT/xedocs/pull/123) should do the trick? @jmosbacher

**Pull request closed without merging**
