### PR TITLE
Allow different format for s1_xyz_maps

### PR DESCRIPTION
**Pull request by shenyangshi**
Related to https://github.com/XENONnT/corrections/pull/232.

### CODE REVIEW

**Comment by jmosbacher** [comment]
@shenyangshi thanks for this. Just wondering if it may be useful also to make available the local file path via a property name something like "local_file" or something that just downloads the file and returns the path using `get_resource` and then have the map property use this property to build the map? just thinking there may be situations that someone would want to load the file and not the map

**Comment by shenyangshi** [comment]
Thanks for the suggestions, now updated :)

**Review by jmosbacher — APPROVED** [review]

**Comment by shenyangshi** [comment]
@jmosbacher Thanks a lot, can we release a xedocs version as well?

**Comment by shenyangshi** [comment]
Sorry I act too fast, let me add.

**Pull request merged**
