### PR TITLE
import mongodownloader from utilix

### PR DESCRIPTION
**Pull request by yuema137**
Keep consistent with: https://github.com/XENONnT/utilix/pull/141

### CODE REVIEW

**Comment by shenyangshi** [comment]
Thanks @yuema137 for the PR. I wasn't closely following the software updates. It seems the essential mongo interface in straxen will also be moved to utilix like in [here](https://github.com/XENONnT/straxen/blob/ee37dc55f71be25da05fa6371b3cafad24937411/straxen/config/protocols.py#L45). Does this we'll treat utilix as dependency for straxen and add it to the base environments?

**Comment by dachengx** [comment]
utilix is already in base_env: https://github.com/XENONnT/base_environment/blob/36b01dbce38ca0362c52cc2f44c78a129d2ce759/extra_requirements/requirements-tests.txt#L52

**Review by dachengx — CHANGES_REQUESTED** [review]
@yuema137 Please put utilix in pyproject.toml.

**Review by dachengx — APPROVED** [review]
Maybe we do not need to put `utilix` in `pyproject.toml`.

**Pull request merged**
