### PR TITLE
Add `z_bias_map` schema

### PR DESCRIPTION
**Pull request by dachengx**
It is a time interval piece-wise correction.

Reference: https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:terliuk:drift_field_z_bias_correction

### CODE REVIEW

**Review by jmosbacher — CHANGES_REQUESTED** [review]
Thanks @dachengx !

Just one thing missing, the fields of the schema :) 
Inheriting from `TimeIntervalCorrection` will add the `version: str` and `time: TimeInterval` fields but there is no fields defined to hold the map.
I see now that the maps will be stored in `private_nt_aux_files` so i guess this schema will only store the file name for each time period? In that case either add a `value: str` field or inherit from the `BaseMap` schema which has a value field of type string.
`from .base_references import BaseMap`, but BaseMap also has the `algorithm` field which may not be relevant.

Another more advanced option would be to add a field called e.g. `filename: str` and add a property named `value` which loads the file when accessed. I didn't do this for the BaseMap class because i was afraid it may confuse people.

**Comment by jmosbacher** [comment]
For simplicity, maybe just make it similar to what we did for all the other maps.

**Comment by jmosbacher** [comment]
Have you had a look at the `BaseResourceReference` class? 
This class checks that the file exists in MongoDB before inserting it into the DB.
Would this kind of check also be useful for this map?

**Comment by dachengx** [comment]
> Have you had a look at the `xedocs.schemas.corrections.base_references.BaseResourceReference` class? This class checks that the file exists in MongoDB before inserting it into the DB. Would this kind of check also be useful for this map?

Sorry, I misunderstood your point. I think `BaseResourceReference` is certainly better.

**Review by jmosbacher — APPROVED** [review]

**Pull request merged**
